import {
  Patient,
  PrenatalVisit,
  UltrasoundImage,
  GBVReport,
  TeleconsultRequest,
  Alert,
  User,
  Clinic,
  ClinicStats,
  AnalyticsData,
  SyncStatus,
} from "./types";

// Mock Users
export const mockUsers: User[] = [
  {
    id: "u1",
    name: "Dr. Amina Hassan",
    email: "amina.hassan@unfpa.org",
    role: "doctor",
    avatar: "/avatars/doctor-1.jpg",
    lastActive: new Date().toISOString(),
    status: "online",
  },
  {
    id: "u2",
    name: "Nurse Fatima Ali",
    email: "fatima.ali@unfpa.org",
    role: "midwife",
    clinic: "Gode Mobile Clinic",
    lastActive: new Date(Date.now() - 3600000).toISOString(),
    status: "online",
  },
  {
    id: "u3",
    name: "Midwife Sara Mohammed",
    email: "sara.mohammed@unfpa.org",
    role: "midwife",
    clinic: "Kebri Dehar Health Center",
    lastActive: new Date(Date.now() - 7200000).toISOString(),
    status: "away",
  },
  {
    id: "u4",
    name: "Admin Yohannes Bekele",
    email: "yohannes.bekele@unfpa.org",
    role: "admin",
    lastActive: new Date().toISOString(),
    status: "online",
  },
];

export const currentUser: User = mockUsers[3]; // Admin user for dashboard

// Mock Clinics
export const mockClinics: Clinic[] = [
  {
    id: "c1",
    name: "Gode Mobile Clinic",
    location: "Gode Town",
    region: "Somali",
    zone: "Nogob",
    woreda: "Gode",
    type: "mobile",
    status: "active",
    staff: ["u2", "u5"],
    patientCount: 342,
    lastSync: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: "c2",
    name: "Kebri Dehar Health Center",
    location: "Kebri Dehar",
    region: "Somali",
    zone: "Nogob",
    woreda: "Kebri Dehar",
    type: "fixed",
    status: "active",
    staff: ["u3", "u6"],
    patientCount: 567,
    lastSync: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "c3",
    name: "Shilabo Mobile Unit",
    location: "Shilabo",
    region: "Somali",
    zone: "Nogob",
    woreda: "Shilabo",
    type: "mobile",
    status: "active",
    staff: ["u7"],
    patientCount: 198,
    lastSync: new Date(Date.now() - 86400000).toISOString(),
  },
];

// Mock Patients
export const mockPatients: Patient[] = [
  {
    id: "p1",
    fullName: "Halima Abdi Omar",
    age: 28,
    dateOfBirth: "1996-03-15",
    idNumber: "ETH-NOG-2024-001",
    phoneNumber: "+251912345678",
    address: "Zone 3, House 45",
    village: "Gode Town",
    emergencyContact: "Hassan Omar (Husband)",
    emergencyPhone: "+251912345679",
    pregnancyStatus: "pregnant",
    gravida: 3,
    para: 2,
    lmpDate: "2024-06-15",
    eddDate: "2025-03-22",
    bloodType: "O+",
    hivStatus: "negative",
    riskLevel: "medium",
    riskScore: 45,
    riskFactors: ["Previous cesarean", "Anemia history"],
    registeredAt: "2024-07-20T10:30:00Z",
    lastVisit: "2024-11-28T14:00:00Z",
    assignedMidwife: "Fatima Ali",
    syncStatus: "synced",
    clinicId: "c1",
  },
  {
    id: "p2",
    fullName: "Amina Mohammed Yusuf",
    age: 22,
    dateOfBirth: "2002-08-10",
    idNumber: "ETH-NOG-2024-002",
    phoneNumber: "+251923456789",
    address: "Kebele 02, House 12",
    village: "Kebri Dehar",
    emergencyContact: "Fatima Yusuf (Mother)",
    emergencyPhone: "+251923456790",
    pregnancyStatus: "pregnant",
    gravida: 1,
    para: 0,
    lmpDate: "2024-08-01",
    eddDate: "2025-05-08",
    bloodType: "A+",
    hivStatus: "negative",
    riskLevel: "low",
    riskScore: 15,
    riskFactors: ["Primigravida"],
    registeredAt: "2024-09-05T09:00:00Z",
    lastVisit: "2024-11-30T11:00:00Z",
    assignedMidwife: "Sara Mohammed",
    syncStatus: "synced",
    clinicId: "c2",
  },
  {
    id: "p3",
    fullName: "Khadija Ibrahim Hassan",
    age: 35,
    dateOfBirth: "1989-12-20",
    idNumber: "ETH-NOG-2024-003",
    phoneNumber: "+251934567890",
    address: "Zone 1, House 78",
    village: "Gode Town",
    emergencyContact: "Ibrahim Hassan (Father)",
    emergencyPhone: "+251934567891",
    pregnancyStatus: "pregnant",
    gravida: 6,
    para: 5,
    lmpDate: "2024-05-20",
    eddDate: "2025-02-24",
    bloodType: "B-",
    hivStatus: "negative",
    riskLevel: "high",
    riskScore: 72,
    riskFactors: [
      "Advanced maternal age",
      "Grand multipara",
      "Previous PPH",
      "Rh negative",
    ],
    registeredAt: "2024-06-10T08:30:00Z",
    lastVisit: "2024-12-01T15:30:00Z",
    assignedMidwife: "Fatima Ali",
    syncStatus: "pending",
    clinicId: "c1",
  },
  {
    id: "p4",
    fullName: "Zahra Ahmed Nur",
    age: 19,
    dateOfBirth: "2005-04-25",
    idNumber: "ETH-NOG-2024-004",
    phoneNumber: "+251945678901",
    address: "Village Center",
    village: "Shilabo",
    emergencyContact: "Ahmed Nur (Father)",
    emergencyPhone: "+251945678902",
    pregnancyStatus: "pregnant",
    gravida: 1,
    para: 0,
    lmpDate: "2024-07-10",
    eddDate: "2025-04-16",
    bloodType: "AB+",
    hivStatus: "unknown",
    riskLevel: "critical",
    riskScore: 85,
    riskFactors: [
      "Teenage pregnancy",
      "Severe preeclampsia",
      "Poor nutrition",
      "No previous ANC",
    ],
    registeredAt: "2024-10-15T11:00:00Z",
    lastVisit: "2024-11-25T10:00:00Z",
    assignedMidwife: "Sara Mohammed",
    syncStatus: "synced",
    clinicId: "c3",
  },
  {
    id: "p5",
    fullName: "Maryam Ali Farah",
    age: 31,
    dateOfBirth: "1993-07-08",
    idNumber: "ETH-NOG-2024-005",
    address: "Kebele 04, House 23",
    village: "Kebri Dehar",
    emergencyContact: "Ali Farah (Husband)",
    emergencyPhone: "+251956789012",
    pregnancyStatus: "postpartum",
    gravida: 4,
    para: 4,
    bloodType: "O-",
    hivStatus: "negative",
    riskLevel: "low",
    riskScore: 20,
    riskFactors: ["Rh negative - monitored"],
    registeredAt: "2024-02-20T14:00:00Z",
    lastVisit: "2024-11-15T09:30:00Z",
    assignedMidwife: "Sara Mohammed",
    syncStatus: "synced",
    clinicId: "c2",
  },
];

// Mock Prenatal Visits
export const mockPrenatalVisits: PrenatalVisit[] = [
  {
    id: "v1",
    patientId: "p1",
    visitDate: "2024-11-28T14:00:00Z",
    visitNumber: 5,
    gestationalAge: { weeks: 24, days: 3 },
    vitals: {
      bloodPressureSystolic: 118,
      bloodPressureDiastolic: 76,
      weight: 68.5,
      temperature: 36.8,
      pulse: 78,
      respiratoryRate: 16,
      fetalHeartRate: 145,
      fundalHeight: 24,
    },
    symptoms: ["Mild back pain", "Occasional heartburn"],
    medications: ["Ferrous sulfate", "Folic acid"],
    labResults: {
      hemoglobin: 11.2,
      urinalysis: "Normal",
      glucoseLevel: 95,
    },
    notes:
      "Patient progressing well. Fetal movements regular. Continue current supplements.",
    nextAppointment: "2024-12-26T14:00:00Z",
    riskFlags: [],
    conductedBy: "Fatima Ali",
    syncStatus: "synced",
  },
  {
    id: "v2",
    patientId: "p3",
    visitDate: "2024-12-01T15:30:00Z",
    visitNumber: 8,
    gestationalAge: { weeks: 28, days: 5 },
    vitals: {
      bloodPressureSystolic: 135,
      bloodPressureDiastolic: 88,
      weight: 75.2,
      temperature: 37.1,
      pulse: 88,
      respiratoryRate: 18,
      fetalHeartRate: 152,
      fundalHeight: 28,
    },
    symptoms: ["Headaches", "Swelling in feet", "Fatigue"],
    medications: ["Ferrous sulfate", "Calcium supplement", "Low-dose aspirin"],
    labResults: {
      hemoglobin: 10.5,
      urinalysis: "Trace protein",
      glucoseLevel: 105,
    },
    notes:
      "BP elevated - monitoring for preeclampsia. Proteinuria detected. Advised bed rest and salt restriction. Teleconsult requested with specialist.",
    nextAppointment: "2024-12-08T10:00:00Z",
    riskFlags: ["Elevated BP", "Proteinuria", "Risk of preeclampsia"],
    conductedBy: "Fatima Ali",
    syncStatus: "pending",
  },
  {
    id: "v3",
    patientId: "p4",
    visitDate: "2024-11-25T10:00:00Z",
    visitNumber: 2,
    gestationalAge: { weeks: 20, days: 1 },
    vitals: {
      bloodPressureSystolic: 148,
      bloodPressureDiastolic: 95,
      weight: 52.0,
      temperature: 36.9,
      pulse: 92,
      respiratoryRate: 20,
      fetalHeartRate: 158,
      fundalHeight: 18,
    },
    symptoms: [
      "Severe headache",
      "Visual disturbances",
      "Epigastric pain",
      "Nausea",
    ],
    medications: ["Methyldopa", "Magnesium sulfate"],
    labResults: {
      hemoglobin: 9.8,
      urinalysis: "2+ protein",
      glucoseLevel: 88,
    },
    notes:
      "CRITICAL: Severe preeclampsia suspected. Initiated antihypertensive therapy. Urgent teleconsult submitted. Patient advised immediate referral if symptoms worsen.",
    nextAppointment: "2024-12-02T09:00:00Z",
    riskFlags: [
      "Severe hypertension",
      "Heavy proteinuria",
      "Preeclampsia symptoms",
      "Requires urgent specialist review",
    ],
    conductedBy: "Sara Mohammed",
    syncStatus: "synced",
  },
];

// Mock Ultrasound Images
export const mockUltrasounds: UltrasoundImage[] = [
  {
    id: "us1",
    patientId: "p1",
    visitId: "v1",
    captureDate: "2024-11-28T14:30:00Z",
    imageUrl: "/ultrasounds/us-sample-1.jpg",
    thumbnailUrl: "/ultrasounds/us-sample-1-thumb.jpg",
    gestationalAge: { weeks: 24, days: 3 },
    findings:
      "Normal fetal development. Adequate amniotic fluid. Placenta anterior, grade I.",
    annotations: ["BPD measured", "FL measured", "Normal cardiac activity"],
    measurements: {
      bpd: 60,
      fl: 44,
      ac: 198,
      hc: 220,
      efw: 650,
    },
    quality: "good",
    capturedBy: "Fatima Ali",
    reviewedBy: "Dr. Amina Hassan",
    reviewStatus: "reviewed",
    syncStatus: "synced",
  },
  {
    id: "us2",
    patientId: "p3",
    visitId: "v2",
    captureDate: "2024-12-01T16:00:00Z",
    imageUrl: "/ultrasounds/us-sample-2.jpg",
    thumbnailUrl: "/ultrasounds/us-sample-2-thumb.jpg",
    gestationalAge: { weeks: 28, days: 5 },
    findings:
      "Fetal growth appropriate for gestational age. Amniotic fluid index 14cm. Placenta posterior.",
    annotations: ["Growth parameters normal", "AFI adequate", "Cervix closed"],
    measurements: {
      bpd: 74,
      fl: 55,
      ac: 252,
      hc: 268,
      efw: 1250,
    },
    quality: "excellent",
    capturedBy: "Fatima Ali",
    reviewStatus: "pending",
    syncStatus: "pending",
  },
  {
    id: "us3",
    patientId: "p4",
    captureDate: "2024-11-25T10:30:00Z",
    imageUrl: "/ultrasounds/us-sample-3.jpg",
    thumbnailUrl: "/ultrasounds/us-sample-3-thumb.jpg",
    gestationalAge: { weeks: 20, days: 1 },
    findings:
      "IUGR suspected - growth below 10th percentile. Reduced amniotic fluid. Recommend close monitoring.",
    annotations: [
      "Small for dates",
      "Oligohydramnios",
      "Increased placental resistance",
    ],
    measurements: {
      bpd: 42,
      fl: 28,
      ac: 140,
      hc: 165,
      efw: 280,
    },
    quality: "fair",
    capturedBy: "Sara Mohammed",
    reviewStatus: "flagged",
    syncStatus: "synced",
  },
];

// Mock GBV Reports
export const mockGBVReports: GBVReport[] = [
  {
    id: "gbv1",
    patientId: "p4",
    reportDate: "2024-11-25T11:00:00Z",
    incidentDate: "2024-11-20",
    incidentType: "physical",
    description:
      "Patient disclosed physical abuse by partner. Multiple bruises observed on arms and back during examination.",
    perpetratorRelation: "Intimate partner",
    injuries:
      "Multiple bruises on upper arms and lower back. No fractures detected.",
    safetyPlan:
      "Patient to stay with aunt for safety. Emergency contact provided. Follow-up counseling scheduled.",
    referrals: [
      "Women's Safe House - Kebri Dehar",
      "Psychosocial Support Center",
    ],
    followUpRequired: true,
    followUpDate: "2024-12-09",
    status: "in_progress",
    confidentialityLevel: "restricted",
    reportedBy: "Sara Mohammed",
    attachments: [],
    syncStatus: "synced",
  },
  {
    id: "gbv2",
    patientId: "p2",
    reportDate: "2024-10-15T09:30:00Z",
    incidentType: "emotional",
    description:
      "Patient reported verbal abuse and isolation from family by in-laws.",
    perpetratorRelation: "In-laws",
    safetyPlan:
      "Family mediation arranged. Patient has support from maternal family.",
    referrals: ["Community Counseling Service"],
    followUpRequired: true,
    followUpDate: "2024-11-15",
    status: "closed",
    confidentialityLevel: "standard",
    reportedBy: "Sara Mohammed",
    attachments: [],
    syncStatus: "synced",
  },
];

// Mock Teleconsult Requests
export const mockTeleconsults: TeleconsultRequest[] = [
  {
    id: "tc1",
    patientId: "p4",
    patientName: "Zahra Ahmed Nur",
    requestedBy: "Sara Mohammed",
    requestDate: "2024-11-25T11:30:00Z",
    priority: "emergency",
    consultationType: "high_risk",
    chiefComplaint:
      "Severe preeclampsia in 19-year-old primigravida at 20 weeks",
    clinicalNotes:
      "BP 148/95, 2+ proteinuria, severe headache with visual disturbances, epigastric pain. IUGR suspected on ultrasound. Patient is undernourished with BMI 17.5.",
    attachments: [
      {
        type: "visit_notes",
        url: "/docs/v3-notes.pdf",
        name: "Visit Notes - Nov 25",
      },
      {
        type: "ultrasound",
        url: "/ultrasounds/us-sample-3.jpg",
        name: "Ultrasound - 20w1d",
      },
      { type: "lab_results", url: "/docs/labs-p4.pdf", name: "Lab Results" },
    ],
    assignedSpecialist: "Dr. Amina Hassan",
    status: "in_review",
    syncStatus: "synced",
  },
  {
    id: "tc2",
    patientId: "p3",
    patientName: "Khadija Ibrahim Hassan",
    requestedBy: "Fatima Ali",
    requestDate: "2024-12-01T16:30:00Z",
    priority: "urgent",
    consultationType: "high_risk",
    chiefComplaint:
      "Rising blood pressure in grand multipara with previous PPH history",
    clinicalNotes:
      "G6P5, 35yo, BP trending up from 125/82 to 135/88 over 2 weeks. Previous postpartum hemorrhage. Rh negative, anti-D given. Trace protein in urine.",
    attachments: [
      {
        type: "visit_notes",
        url: "/docs/v2-notes.pdf",
        name: "Visit Notes - Dec 1",
      },
      {
        type: "ultrasound",
        url: "/ultrasounds/us-sample-2.jpg",
        name: "Ultrasound - 28w5d",
      },
    ],
    status: "pending",
    syncStatus: "pending",
  },
  {
    id: "tc3",
    patientId: "p1",
    patientName: "Halima Abdi Omar",
    requestedBy: "Fatima Ali",
    requestDate: "2024-11-15T10:00:00Z",
    priority: "routine",
    consultationType: "ultrasound_review",
    chiefComplaint:
      "Routine ultrasound review - previous cesarean scar assessment",
    clinicalNotes:
      "G3P2, 28yo, history of 2 previous cesarean sections. Current pregnancy at 20 weeks. Request review of lower uterine segment and placental position.",
    attachments: [
      {
        type: "ultrasound",
        url: "/ultrasounds/us-review.jpg",
        name: "Ultrasound - 20w",
      },
    ],
    assignedSpecialist: "Dr. Amina Hassan",
    status: "responded",
    response: {
      respondedBy: "Dr. Amina Hassan",
      respondedAt: "2024-11-16T14:00:00Z",
      diagnosis:
        "Previous cesarean scars appear well-healed. Placenta posterior, clear of scar site.",
      recommendations:
        "Continue routine antenatal care. Repeat ultrasound at 32 weeks to reassess placental position. Plan for elective cesarean at 38-39 weeks given 2 previous sections.",
      followUpInstructions:
        "Schedule repeat ultrasound at 32 weeks. Continue current supplements. Report any vaginal bleeding immediately.",
      prescriptions: [
        "Continue ferrous sulfate 200mg daily",
        "Continue folic acid 5mg daily",
      ],
    },
    syncStatus: "synced",
  },
];

// Mock Alerts
export const mockAlerts: Alert[] = [
  {
    id: "a1",
    type: "risk",
    priority: "critical",
    title: "Critical Risk Alert",
    message:
      "Patient Zahra Ahmed Nur (ETH-NOG-2024-004) has critical risk score. Immediate specialist review required.",
    patientId: "p4",
    patientName: "Zahra Ahmed Nur",
    createdAt: "2024-11-25T11:35:00Z",
    actionRequired: true,
    actionUrl: "/patients/p4",
  },
  {
    id: "a2",
    type: "teleconsult",
    priority: "high",
    title: "Urgent Teleconsult Pending",
    message:
      "Emergency teleconsult for Zahra Ahmed Nur awaiting specialist review.",
    patientId: "p4",
    patientName: "Zahra Ahmed Nur",
    createdAt: "2024-11-25T11:32:00Z",
    actionRequired: true,
    actionUrl: "/teleconsult/tc1",
  },
  {
    id: "a3",
    type: "appointment",
    priority: "medium",
    title: "Upcoming Appointments Today",
    message:
      "3 prenatal checkup appointments scheduled for today at Gode Mobile Clinic.",
    createdAt: new Date().toISOString(),
    actionRequired: false,
    actionUrl: "/appointments",
  },
  {
    id: "a4",
    type: "sync",
    priority: "low",
    title: "Sync Completed",
    message: "Shilabo Mobile Unit synchronized 23 records successfully.",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    readAt: new Date(Date.now() - 3000000).toISOString(),
    actionRequired: false,
  },
  {
    id: "a5",
    type: "risk",
    priority: "high",
    title: "Elevated Risk Detected",
    message:
      "Patient Khadija Ibrahim Hassan showing signs of potential preeclampsia. Review recommended.",
    patientId: "p3",
    patientName: "Khadija Ibrahim Hassan",
    createdAt: "2024-12-01T16:00:00Z",
    actionRequired: true,
    actionUrl: "/patients/p3",
  },
  {
    id: "a6",
    type: "gbv",
    priority: "high",
    title: "GBV Case Follow-up Due",
    message:
      "Scheduled follow-up for GBV case (ID: gbv1) is due on December 9, 2024.",
    patientId: "p4",
    createdAt: "2024-12-06T08:00:00Z",
    actionRequired: true,
    actionUrl: "/gbv/gbv1",
  },
];

// Mock Clinic Stats
export const mockClinicStats: ClinicStats = {
  totalPatients: 1107,
  activePregnancies: 423,
  highRiskPatients: 67,
  visitsThisMonth: 312,
  teleconsultsThisMonth: 28,
  gbvReportsThisMonth: 4,
  syncPendingCount: 15,
  appointmentsToday: 8,
};

// Mock Analytics Data
export const mockAnalyticsData: AnalyticsData = {
  visitsByMonth: [
    { month: "Jun", visits: 245, newPatients: 42 },
    { month: "Jul", visits: 268, newPatients: 38 },
    { month: "Aug", visits: 289, newPatients: 45 },
    { month: "Sep", visits: 301, newPatients: 51 },
    { month: "Oct", visits: 298, newPatients: 47 },
    { month: "Nov", visits: 312, newPatients: 53 },
  ],
  riskDistribution: [
    { level: "Low", count: 892 },
    { level: "Medium", count: 148 },
    { level: "High", count: 52 },
    { level: "Critical", count: 15 },
  ],
  topRiskFactors: [
    { factor: "Anemia", count: 89 },
    { factor: "Previous cesarean", count: 67 },
    { factor: "Advanced maternal age", count: 54 },
    { factor: "Hypertension", count: 48 },
    { factor: "Teenage pregnancy", count: 42 },
    { factor: "Grand multipara", count: 38 },
    { factor: "Malnutrition", count: 35 },
    { factor: "Previous PPH", count: 28 },
  ],
  teleconsultMetrics: {
    totalRequests: 156,
    avgResponseTime: 4.2,
    pendingCount: 8,
    resolvedCount: 148,
  },
  gestationalAgeDistribution: [
    { range: "0-12 weeks", count: 78 },
    { range: "13-20 weeks", count: 95 },
    { range: "21-28 weeks", count: 112 },
    { range: "29-36 weeks", count: 98 },
    { range: "37+ weeks", count: 40 },
  ],
};

// Mock Sync Status
export const mockSyncStatus: SyncStatus = {
  lastSyncTime: new Date(Date.now() - 1800000).toISOString(),
  pendingUploads: 12,
  pendingDownloads: 3,
  conflicts: 1,
  isOnline: true,
};

